---
title: "Lecture5 Tutorial Exercises"
author: "Xiang Li"
date: "2023/11/7"
output: pdf_document
---
```{r}
library(matlib)
```
# Exercise 3.3.1
## c
```{r}
A = matrix(c(7, 0, -4, 0, 5, 0, 5, 0, -2), nrow = 3, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
```
## d
```{r}
A = matrix(c(1, 1, -3, 2, 0, 6, 1, -1, 5), nrow = 3, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  print(C)
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
```
## e
```{r}
A = matrix(c(1, -2, 3, 2, 6, -6, 1, 2, -1), nrow = 3, byrow = TRUE)
e_values = eigen(A)$values
e_values
```
## f
```{r}
A = matrix(c(0, 1, 0, 3, 0, 1, 2, 0, 0), nrow = 3, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
```
