---
title: "Lecture9 Tutorial Exercises"
author: "Xiang Li"
date: "2023/11/19"
output: pdf_document
---
# Exercise 8.2.5
## a
```{r}
A = matrix(c(0, 1, 1, 0), nrow = 2, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
eigen(A)$vectors
```
## b
```{r}
A = matrix(c(1, -1, -1, 1), nrow = 2, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
eigen(A)$vectors
```
## d
```{r}
A = matrix(c(3, 0, 7, 0, 5, 0, 7, 0, 3), nrow = 3, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
eigen(A)$vectors
```
## g
```{r}
A = matrix(c(5, 3, 0, 0, 3, 5, 0, 0, 0, 0, 7, 1, 0, 0, 1, 7), nrow = 4, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
eigen(A)$vectors
```
## h
```{r}
A = matrix(c(3, 5, -1, 1, 5, 3, 1 ,-1, -1, 1, 3, 5, 1, -1, 5, 3), nrow = 4, byrow = TRUE)
e_values = eigen(A)$values
e_values
n = length(e_values)
nrow_ = nrow(A)
b = replicate(nrow_, 0)
for (i in 1:n){
  C = e_values[i]*diag(nrow_)-A
  i_vector = gaussianElimination(C, b)
  print(i_vector)
}
eigen(A)$vectors
```
