---
title: "Lecture 5 - Visualizing Associations"
author: "dr. Ethan McCormick"
date: "2023-03-09"
output:
  ioslides_presentation:
    widescreen: yes
    fig_width: 4.5
    fig_height: 3.2
subtitle: Data Visualisation
editor_options:
  markdown:
    wrap: 72
---

```{css, echo=FALSE}
pre {
  max-height: 700px;
  overflow-y: auto;
}

pre[class] {
  max-height: 400px;
}
```

```{=html}
<style>
.first-column {
    width: 55%;
    padding: 0 10px 0 0;
    float: left;
}

.second-column {
    width: 40%;
    padding: 0 10px 0 0;
    float: left;
}
</style>
```
```{=html}
<style>
.first-column-3 {
    width: 32%;
    padding: 0 10px 0 0;
    float: left;
}

.second-column-3 {
    width: 32%;
    padding: 0 10px 0 0;
    float: left;
}

.third-column-3 {
    width: 32%;
    padding: 0 10px 0 0;
    float: left;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, errors = FALSE, message = FALSE, cache = TRUE)
```

```{r}
#| echo: false
#| warnings: false
library(ggplot2)
library(dplyr)
nytimes_theme <- function(c_bg = "grey95", ...) {
  
  ## Colors — stick with the ggplot2() greys
  #c_bg <- c_bg
  c_grid  <- "grey80"
  c_btext <- "grey5"
  c_mtext <- "grey30"
  
  # Begin construction of chart
  ggplot2::theme_bw(base_size = 12, base_family = "Helvetica") +
    
    # Region
    ggplot2::theme(
      panel.background = ggplot2::element_rect(fill = c_bg, color = c_bg),
      plot.background  = ggplot2::element_rect(fill = c_bg, color = c_bg),
      panel.border     = ggplot2::element_rect(color = c_bg)
    ) +
    
    # Grid
    ggplot2::theme(
      panel.grid.major = ggplot2::element_line(color = c_grid, size = .25),
      panel.grid.minor = ggplot2::element_blank(),
      axis.ticks       = ggplot2::element_blank()
    ) +
    
    # Legend
    ggplot2::theme(
      legend.position = c(0, 1),
      legend.justification = c(0, 1),
      legend.key           = ggplot2::element_rect(fill = NA, color = NA),
      legend.background    = ggplot2::element_rect(fill = "transparent", color = NA),
      legend.text          = ggplot2::element_text(color = c_mtext)
    ) +
    
    # Titles, labels, etc.
    ggplot2::theme(
      plot.title     = ggplot2::element_text(
        color = c_btext,
        vjust = 1.25,
        face = "bold",
        size = 18
      ),
      axis.text      = ggplot2::element_text(size = 10, color = c_mtext),
      axis.title.x   = ggplot2::element_text(
        size = 12,
        color = c_mtext,
        hjust = 0.5
      ),
      axis.title.y   = ggplot2::element_text(
        size = 12,
        color = c_mtext,
        hjust = 0.5
      )
    ) +
    # Facets
    ggplot2::theme(
      strip.background = ggplot2::element_rect(fill = c_bg, color = c_btext),
      strip.text = ggplot2::element_text(size = 10, color = c_btext)
    ) +
    
    # Plot margins
    ggplot2::theme(plot.margin = ggplot2::unit(c(0.35, 0.2, 0.3, 0.35), "cm")) +
    
    # Additionals
    ggplot2::theme(...)
}

load("Exercises/blue_jays.rda")

mHealth <- read.csv("Exercises/mentalhealth.csv")

penguins <- palmerpenguins::penguins

load("Exercises/cancer.rda")

load("Exercises/household.rda")
```

```{r}
#| echo: false
#| fig.align: center
#| out.width: 100%

ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,            
                y = Head)) + 
  geom_point() + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)")
```


```{r}
#| echo: false
#| fig.align: center
#| out.width: 100%

ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)")
```


```{r}
#| echo: false
#| fig.align: center
#| out.width: 100%

ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5,
             color = "firebrick") + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)")
```


```{r}
#| echo: false
#| fig.align: center
#| out.width: 100%

library(ggExtra)

p <- ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") 

ggMarginal(p, type = "density")

ggMarginal(p, type = "histogram")

ggMarginal(p, type = "densigram")
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

p <- ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") 

ggMarginal(p, type = "densigram",
           color = "black",
           fill = "blue",
           alpha = 0.5)
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

p <- ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") 

ggMarginal(p, type = "densigram",
           xparams = list(
             color = "black",
             fill = "blue",
             alpha = 0.5))
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

p <- ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") 

ggMarginal(p, type = "densigram",
           color = "black",
           alpha = 0.5,
           xparams = list(
             fill = "blue"),
           yparams = list(
             fill = "red"))
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

p <- ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") 

ggMarginal(p, type = "densigram",
           margins = "y",
           color = "black",
           alpha = 0.5,
           fill = "green")
```

```{r}
#| echo: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head,
                color = factor(
                  Sex,
                  labels = c("Female", 
                             "Male")))) + 
  geom_point(size = 2, 
             alpha = 0.75) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)",
       color = "Sex") +
  ggsci::scale_color_startrek() + 
  theme(legend.justification = c(1, 0), 
        legend.position = c(0.99, 0.01))
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head,
                color = factor(
                  Sex,
                  labels = c("Female", 
                             "Male")))) + 
  geom_point(size = 2, 
             alpha = 0.75) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)",
       color = "Sex") +
  ggsci::scale_color_startrek() + 
  theme(legend.justification = c(1, 0), 
        legend.position = c(0.99, 0.01)) -> p

ggMarginal(p, type = "densigram",
           groupColour = TRUE,
           groupFill = TRUE)
```



```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 5
#| fig.width: 5
#| out.width: 100%

ggplot(
  data = blue_jays, 
  mapping = aes(x = Mass,
                y = Head,
                color = factor(
                  Sex,
                  labels = c("Female", 
                             "Male")),
                size = Skull)) + 
  geom_point(alpha = 0.75) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)",
       color = "Sex",
       size = "Skull Size (mm)") +
  ggsci::scale_color_startrek() +
  theme(legend.position = "top", 
        legend.box = "vertical",
        legend.direction = "horizontal") 
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggplot(data = mHealth, 
       mapping = aes(x = depress,
                     y = anxiety)) + 
  geom_point(alpha = 1) + 
  labs(x = "Depression Symptoms", 
       y = "Anxiety Symptoms") 
```



```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggplot(data = mHealth, 
       mapping = aes(x = depress,
                     y = anxiety)) + 
  geom_point(alpha = 0.1) + 
  labs(x = "Depression Symptoms", 
       y = "Anxiety Symptoms") 
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggplot(
  data = mHealth, 
  mapping = aes(x = depress,
                y = anxiety)) + 
  geom_count(alpha = 0.75) + 
  labs(x = "Depression Symptoms", 
       y = "Anxiety Symptoms") +
  scale_size_continuous(
    breaks = c(25, 50, 75, 100)) +
  labs(size = "Count")
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggplot(
  blue_jays, 
  aes(x = Mass,
      y = Head,
      color = factor(Sex,
                     labels = c("Female", 
                                "Male")),
      size = Skull)) + 
  geom_point(alpha = 0.75) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)",
       color = "Sex",
       size = "Skull Size (mm)") +
  facet_grid(~factor(Sex, 
                     labels = c("Female","Male"))) +
  ggsci::scale_color_startrek(guide = "none") +
  theme(legend.position = "top", 
        legend.box = "vertical",
        legend.direction = "horizontal") 
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

library(GGally)

ggpairs(blue_jays[,c("Head",
                     "Mass",
                     "Skull")])
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggpairs(blue_jays,
        columns = c("Head","Mass","Skull"),
        mapping = aes(color = factor(
          Sex,
          labels = c("Female",
                     "Male")),
          alpha = 0.5))
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 5
#| fig.width: 6
#| out.width: 100%

ggpairs(blue_jays |> mutate(Sex = factor(Sex)),
        columns = c("Head","Mass","Skull","Sex"),
        mapping = aes(color = factor(Sex,
                                     labels = c("Female",
                                                "Male")),
                      alpha = 0.5))
```


```{r}
#| eval: false
#| 
my_scatter <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_point(color='darkgrey', alpha=.1) +
    geom_smooth(method='lm', se=TRUE, formula='y ~ x', color='black')
}

pairs = ggpairs(simpleRTid %>% select(B_LOGRT.Median, PSI.Median, BETAT.Median, PHI.Median),
                columnLabels = c('mu','psi','beta[t]','varphi'), 
                labeller = label_parsed,
                lower = list(continuous = my_scatter),
                diag = list(continuous = 'barDiag'))

# Add Colors for Distributions
pairs[1,1] = pairs[1,1] + aes(fill='x') + 
  scale_fill_manual(values=c('#F8766D')) + 
  theme(legend.position = 'none')
pairs[2,2] = pairs[2,2] + aes(fill='x') + 
  scale_fill_manual(values=c('#00BF7D')) + 
  theme(legend.position = 'none')
pairs[3,3] = pairs[3,3] + aes(fill='x') + 
  scale_fill_manual(values=c('#00B0F6')) + 
  theme(legend.position = 'none')
pairs[4,4] = pairs[4,4] + aes(fill='x') + 
  scale_fill_manual(values=c('#E76BF3')) + 
  theme(legend.position = 'none')

# Manually Add MAP Estimates from Mplus
pairs[1,2] = ggally_text(paste('Corr:\n0.397***'), 
                         color='#717171', 
                         size=3.88,
                         hjust=0.5, 
                         vjust=0.5) +
  theme(strip.background = element_blank(), 
        axis.line = element_line(colour = "grey"), 
        panel.grid.major = element_blank(), 
        panel.border = element_rect(color = "grey95", 
                                    fill = NA, 
                                    size = 1))
pairs[1,3] = ggally_text(paste('Corr:\n-0.515***'), 
                         color='#717171', 
                         size=3.88, 
                         hjust=0.5,
                         vjust=0.5) + 
  theme(strip.background = element_blank(), 
        axis.line = element_line(colour = "grey"), 
        panel.grid.major = element_blank(), 
        panel.border = element_rect(color = "grey95", 
                                    fill = NA,
                                    size = 1))
pairs[1,4] = ggally_text(paste('Corr:\n0.262***'), 
                         color='#717171', 
                         size=3.88, 
                         hjust=0.5,
                         vjust=0.5) + 
  theme(strip.background = element_blank(), 
        axis.line = element_line(colour = "grey"), 
        panel.grid.major = element_blank(), 
        panel.border = element_rect(color = "grey95", 
                                    fill = NA,
                                    size = 1))
pairs[2,3] = ggally_text(paste('Corr:\n-0.181***'), 
                         color='#717171', 
                         size=3.88,
                         hjust=0.5,
                         vjust=0.5) + 
  theme(strip.background = element_blank(), 
        axis.line = element_line(colour = "grey"),
        panel.grid.major = element_blank(), 
        panel.border = element_rect(color = "grey95",
                                    fill = NA,
                                    size = 1))
pairs[2,4] = ggally_text(paste('Corr:\n0.124**'), 
                         color='#717171',
                         size=3.88,
                         hjust=0.5, 
                         vjust=0.5) + 
  theme(strip.background = element_blank(), 
        axis.line = element_line(colour = "grey"), 
        panel.grid.major = element_blank(), 
        panel.border = element_rect(color = "grey95", 
                                    fill = NA, 
                                    size = 1))
pairs[3,4] = ggally_text(paste('Corr:\n-0.134***'), 
                         color='#717171',
                         size=3.88, 
                         hjust=0.5, 
                         vjust=0.5) + 
  theme(strip.background = element_blank(),
        axis.line = element_line(colour = "grey"), 
        panel.grid.major = element_blank(), 
        panel.border = element_rect(color = "grey95", 
                                    fill = NA, 
                                    size = 1))

pairs
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggcorr(blue_jays) +
  theme(legend.justification = c(0, 1), 
        legend.position = c(0.01, 0.75))
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggcorr(penguins) +
  theme(legend.justification = c(0, 1), 
        legend.position = c(0.01, 0.75))
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggcorr(penguins, nbreaks = 5) +
  theme(legend.justification = c(0, 1), 
        legend.position = c(0.01, 0.75))
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggcorr(penguins, geom = "circle") +
  theme(legend.justification = c(0, 1), 
        legend.position = c(0.01, 0.75))
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggcorr(penguins, geom = "circle", label = TRUE) +
  theme(legend.justification = c(0, 1), 
        legend.position = c(0.01, 0.75))
```



```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

ggcorr(penguins, geom = "tile", label = TRUE) +
  theme(legend.justification = c(0, 1), 
        legend.position = c(0.01, 0.75))
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

library(corrplot)

corrplot(cor(penguins[,3:6], 
             use = "complete.obs"))
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

corrplot(cor(penguins[,3:6], 
             use = "complete.obs"),
         method = "number")
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

corrplot(cor(penguins[,3:6], 
             use = "complete.obs"),
         method = "color")
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 4
#| fig.width: 5
#| out.width: 100%

corrplot(cor(penguins[,3:6], 
             use = "complete.obs"),
         method = "ellipse")
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

ggplot(blue_jays, aes(x = Mass,
                      y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") 
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

ggplot(blue_jays, aes(x = Mass,
                      y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") +
  geom_smooth(method = "lm", 
              formula = "y ~ x",
              se = FALSE,
              color = "blue",
              linetype = 2)
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

ggplot(blue_jays, aes(x = Mass,
                      y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") +
  geom_smooth(method = "lm", 
              formula = "y ~ x",
              se = TRUE,
              color = "blue",
              linetype = 2)
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| out.width: 100%

ggplot(blue_jays, aes(x = Mass,
                      y = Head)) + 
  geom_point(size = 2, 
             alpha = 0.5) + 
  labs(x = "Body Mass (g)", 
       y = "Head Length (mm)") +
  geom_smooth(method = "loess",
              se = TRUE,
              color = "blue",
              linetype = 2)
```

```{r}
#| eval: false

ggplot(blue_jays, 
       aes(x = rank(Mass),
           y = rank(Head))) + 
  geom_point(alpha = 0.75) + 
  labs(x = "Body Mass Rank", 
       y = "Head Length Rank") +
  geom_smooth(method = "lm", 
              formula = "y ~ x",
              se = TRUE,
              color = "blue",
              linetype = 2) 
```

```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 2
#| fig.width: 3
#| out.width: 95%

ggplot(blue_jays, 
       aes(x = rank(Mass),
           y = rank(Head))) + 
  geom_point(alpha = 0.75) + 
  labs(x = "Body Mass Rank", 
       y = "Head Length Rank") +
  geom_smooth(method = "lm", 
              formula = "y ~ x",
              se = TRUE,
              color = "blue",
              linetype = 2)
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 7
#| fig.width: 9
#| out.width: 70%

my_scatter <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_point(color='darkgrey', alpha=.1) +
    geom_smooth(method='lm', se=TRUE, formula='y ~ x', color='black') +
    scale_y_continuous(breaks=scales::pretty_breaks()) +
    scale_x_continuous(breaks=scales::pretty_breaks())
}

my_hist <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_histogram(color = 'black', 
                   alpha=0.5,
                   fill = "darkblue") +
    scale_y_continuous(breaks=scales::pretty_breaks()) +
    scale_x_continuous(breaks=scales::pretty_breaks())
}

ggpairs(household,
        lower = list(continuous = my_scatter),
        diag = list(continuous = my_hist),
        columns = c(1:3, 7:9),
        columnLabels = c("Food Share", "Fuel Share", "Clothing Share",
                         "Age", "Ln(Income)", "Ln(Total Expenses)")) + nytimes_theme(c_bg = "white")
```


```{r}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.height: 7
#| fig.width: 9
#| out.width: 75%

library(ggrepel)

ggplot(data = cancer, aes(x = Year, y = Survival, group = Type)) +
  geom_line(aes(color = Type, alpha = 1), size = 1) +
  geom_text_repel(data = subset(cancer, Year == "5 Year"),
            aes(label = Type), 
            size = 2.5, 
            nudge_x = -0.5,
            fontface = "bold") +
  geom_text_repel(data = subset(cancer, Year == "20 Year"),
            aes(label = Type), 
            size = 2.5, 
            nudge_x = 0.5,
            fontface = "bold") +
  geom_label(aes(label = Survival), 
             size = 2.5, 
             label.padding = unit(0.05, "lines"), 
             label.size = 0.0) +
  labs(
    title = "Estimates of Percent Survival Rates",
    subtitle = "Based on: Edward Tufte, Beautiful Evidence, 174, 176.",
    caption = "https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0003nk"
    ) + 
  nytimes_theme(c_bg = "white", 
                panel.grid.major = element_blank(), 
                panel.grid.minor = element_blank()) + 
  scale_x_discrete(position = "top") +
  scale_y_continuous(name = "Survival Rate",
                     labels = scales::percent_format(scale = 1)) +
  theme(legend.position = "none")
```

