---
title: "WorkGroup1"
author: "Group19: Xiang Li, Jiayi Jiang"
date: "2024/3/6"
output: pdf_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(tidy_opts = list(width.cutoff = 55), tidy = TRUE)
```
```{r}
library(eurostat)
library(dtplyr)
library(readr)
library(reshape2)
library(tidyr)
library(ggplot2)
```
```{r}
gdp_df = get_eurostat("nama_10_gdp")
write_csv(gdp_df, file = "data/gdp.csv")
gdp_df_wide = dcast(gdp_df, geo + unit + TIME_PERIOD ~ na_item, value.var = 'values')
gdp_df_wide = dplyr::rename(gdp_df_wide, GDP = 'B1G', FCE= 'P3', AIC = 'P41', GCF = 'P5G', EGS = 'P6', EG="P61",ES="P62",IGS="P7",IG="P71",IS="P72",CE="D1",TPI="D2")
gdp_df_wide = gdp_df_wide[, c('geo', 'unit', 'TIME_PERIOD', 'GDP', 'FCE', 'AIC', 'GCF', 'EGS', 'EG', 'ES', 'IGS', 'IG', 'IS', 'CE', 'TPI')]
write_csv(gdp_df_wide, file = "data/gdp_wide.csv")
# GDP=value added,gross;FCE=Final consumption expenditure;AIC=Actual individual consumption;GCF=Gross capital formation;EGS=Exports of goods and services;EG=Exports of goods;ES=Exports of services;IGS=lmports of goods and services;IG=Imports of goods;IS=Imports of services;CE=Compensation of employees;TPI=Taxes on production and imports
```
```{r}
gdp_df_wide = read.csv('data/gdp_wide.csv')
gdp_df_wide$TIME_PERIOD = as.Date(gdp_df_wide$TIME_PERIOD)
```
## Bar plot of GDP,2023
```{r}
df1 = gdp_df_wide[(gdp_df_wide$TIME_PERIOD == '2023-01-01') & !(gdp_df_wide$geo %in% c('EU27_2020', 'EU28', 'EU15', 'EA', 'EA12', 'EA19', 'EA20')) & (gdp_df_wide$unit == 'CP_MEUR'), ]
ggplot(data = df1, mapping = aes(x = reorder(x = geo, X = GDP, FUN = 'identity'), y = GDP)) +
geom_bar(stat = 'identity', fill = 'blue', alpha = 0.4) +
labs(x = 'country', y = 'GDP, 2023') + coord_flip()
```
## Stacked bar plot of Exports of goods and services
```{r}
df2 = gdp_df_wide[(gdp_df_wide$TIME_PERIOD == '2023-01-01') & !(gdp_df_wide$geo %in% c('EU27_2020', 'EU28', 'EU15', 'EA', 'EA12', 'EA19', 'EA20')) & (gdp_df_wide$unit == 'CP_MEUR'), c('geo', 'EG', 'ES')]
df2 = melt(df2, id.vars = 'geo')
colnames(df2)[2] = 'type'
levels(df2$type)[which(levels(df2$type) == 'EG')] = 'Goods'
levels(df2$type)[which(levels(df2$type) == 'ES')] = 'Services'
ggplot(data = df2, mapping = aes(x = geo, y = value, fill = type)) +
geom_bar(stat = 'identity') +
labs(x = 'country', y = 'Exports of goods and services, 2023')
```
## plot of Compensation of employees
```{r}
df3 = gdp_df_wide[(gdp_df_wide$TIME_PERIOD >= '2000-01-01') & (gdp_df_wide$geo %in% c("FR","NL","SE","UK")) & (gdp_df_wide$unit == 'CP_MNAC'),]
ggplot(data = df3, mapping = aes(x = TIME_PERIOD, y = CE, color = geo, linetype = geo)) +
  geom_line() +
  theme_classic() +
  scale_color_manual(values = c("red","blue","black","brown")) +
  labs(x = "Time", y= "", title="Compensation of employees",
       subtitle = "4 countries:France  Netherlands  Sweden  United Kingdom") +
  guides(color = guide_legend(title = 'country'), linetype = guide_legend(title = 'country'))
```
