---
title: "Statistics CH8"
author: "Xiang Li"
date: "2023/10/26"
output: pdf_document
---
# 8.1.0.1 Exercise
```{r}
Observed = matrix(c(30,50,20,60),nrow=2,byrow=TRUE)
p_hat = (30+20)/160
Expected = matrix(c(80*p_hat,80*(1-p_hat),80*p_hat,80*(1-p_hat)),nrow=2,byrow=TRUE)
T = sum((Observed - Expected)**2/Expected)
T1 = qchisq(0.95, df = 1)
T2 = qchisq(0.9, df = 1)
c(T, T1, T2)
```
# 8.1.1.1 Exercise
## a.
```{r}
X = c(983, 1041, 1026, 1025, 1033, 968, 1028)
mu0 = 1000
sigma = 25
n = length(X)
Z = (mean(X) - mu0)/(sigma/n**0.5)
Z
```
## b.
```{r}
Z_cv1 = qnorm(0.975, mean = 0 , sd = 1)
Z_cv1
```
## c.
```{r}
Z > Z_cv1
```
## d.
```{r}
power = function(mu){
  pnorm(-Z_cv1, mean = (mu-mu0)/(sigma/n**0.5), sd = 1) + pnorm(Z_cv1, mean = (mu-mu0)/(sigma/n**0.5), sd = 1, lower.tail = FALSE)
}
power(980)
```
## e.
```{r}
mu_v = seq(950, 1050, 1)
power_v = power(mu_v)
plot(mu_v, power_v, type = 'l')
```
# 8.1.1.2 Exercise
```{r}
power = function(mu){
  X1 = rnorm(1e5, mean = (mu-mu0)/(sigma/n**0.5), sd = 1)
  mean(X1 < -Z_cv1 | X1 > Z_cv1)
}
power(980)
```
# 8.1.1.3 Exercise
```{r}
Z_cv2 = qnorm(0.95, mean = 0 , sd = 1)
Z_cv2
power2 = function(mu){
  pnorm(-Z_cv1, mean = (mu-mu0)/(sigma/n**0.5), sd = 1)
}
power2_v = power2(mu_v)
plot(mu_v, power2_v, type = 'l')
```
# 8.1.2.2 Exercise
## a.
```{r}
X = c(983, 1041, 1026, 1025, 1033, 968, 1028)
mu0 = 1000
n = length(X)
t = (mean(X) - mu0)/(sd(X)/n**0.5)
t
```
## b.
```{r}
t_cv = qt(0.975, df = n-1)
t_cv
```
## c.
```{r}
abs(t) > t_cv
```
## d.
```{r}
power = function(mu){
  k = 1e5
  rej = numeric(k)
  for (i in 1:k){
    X1 = rnorm(n, mean = mu, sd = sd(X))
    t1 = (mean(X1) - mu0)/(sd(X1)/n**0.5)
    rej[i] = abs(t1) > t_cv
  }
  mean(rej)
}
power(980)
```
# 8.2.0.1 Exercise
```{r}
x=140
n=250
p0=seq(0.05,0.95,0.001)
z=(x - n*p0)/sqrt(n*p0*(1-p0))
reject=abs(z)>1.96
cbind(p0,z,reject)
```
# 8.2.0.2 Exercise
```{r}
x=140
n=250
p0=seq(0.05,0.95,0.001)
z_cv = pnorm(0.95)
z=(x - n*p0)/sqrt(n*p0*(1-p0))
reject=abs(z)>z_cv
a = cbind(p0,z,reject)
# c(0.534, 0.585)
```
# 8.2.1.3 Exercise
```{r}
X = c(983, 1041, 1026, 1025, 1033, 968, 1028)
mu0 = 950:1050
sigma = 25
n = length(X)
Z = (mean(X) - mu0)/(sigma/n**0.5)
Z_cv = qnorm(0.975)
rej = abs(Z) > Z_cv
test = as.data.frame(cbind(mu0, Z, rej))
test$mu0[test$rej == 0]
```
