library(dagitty)

# g = dagitty('dag {
#   BPMEDS [exposure]
#   DEATH   [outcome]
#   BPMEDS   -> { HYPERTEN  ANGINA HOSPMI STROKE CVD DEATH }
#   SEX  -> { EDUC SYSBP DIABP CURSMOKE BMI HEARTRTE HYPERTEN ANGINA HOSPMI STROKE CVD DEATH }
#   AGE  -> { EDUC SYSBP DIABP HYPERTEN ANGINA HOSPMI STROKE CVD DEATH }
#   CURSMOKE -> { SYSBP DIABP HYPERTEN ANGINA HOSPMI STROKE CVD DEATH }
#   SYSBP -> { BPMEDS HEARTRTE }
#   DIABP -> { BPMEDS HEARTRTE }
#   EDUC -> { BPMEDS CURSMOKE BMI DEATH }
#   BMI -> { SYSBP DIABP HEARTRTE HYPERTEN DEATH }
#   HEARTRTE  ->  DEATH
#   HOSPMI -> { ANGINA DEATH }
#   STROKE -> DEATH
#   CVD -> DEATH
#   HYPERTEN -> { ANGINA HOSPMI STROKE CVD DEATH}
#   }
# ')
g = dagitty('dag {
  BPMEDS [exposure]
  DEATH   [outcome]
  BPMEDS   -> { HYPERTEN  ANGINA HOSPMI STROKE CVD DEATH }
  SEX  -> { EDUC SYSBP DIABP CURSMOKE BMI HYPERTEN DEATH }
  AGE  -> { EDUC SYSBP DIABP HYPERTEN DEATH }
  CURSMOKE -> { SYSBP DIABP HYPERTEN DEATH }
  SYSBP -> { BPMEDS HEARTRTE }
  DIABP -> { BPMEDS HEARTRTE }
  EDUC -> { BPMEDS CURSMOKE BMI DEATH }
  BMI -> { SYSBP DIABP HYPERTEN DEATH }
  HEARTRTE  ->  DEATH
  ANGINA -> DEATH
  HOSPMI -> DEATH
  STROKE -> DEATH
  CVD -> DEATH
  HYPERTEN -> { ANGINA HOSPMI STROKE CVD DEATH }
  }
')
jpeg(file="dag.jpg")
plot(g)
dev.off()
# Listing all adjustment sets
adjset = adjustmentSets(g, type = "minimal")
print(1)
