library(dagitty)

g = dagitty('dag {
  BPMEDS   -> { SYSBP DIABP HEARTRTE }
  SEX  -> { SYSBP DIABP CURSMOKE BMI HEARTRTE }
  AGE  -> { SYSBP DIABP HEARTRTE BMI EDUC DEATH }
  CURSMOKE -> DEATH
  EDUC -> { BPMEDS DEATH }
  BMI -> { SYSBP DIABP HEARTRTE }
  HEARTRTE  -> { ANGINA HOSPMI STROKE CVD }
  ANGINA -> CVD
  HOSPMI -> { CVD DEATH }
  STROKE -> DEATH
  CVD -> { STROKE DEATH }
  HYPERTEN -> { BPMEDS ANGINA HOSPMI STROKE CVD DEATH}
  }
')
plot(g)
