---
title: "Group Assignment15"
author: "Jiayi Jiang, Jinrui Du, Xiang Li"
date: "2024/3/11"
output: pdf_document
---
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```
```{r}
library(dagitty)
library(ggplot2)
library(GGally)
library(stdReg)
library(cobalt)
library(gridExtra)
library(survey)
```
# Week3
```{r, fig.height = 8, fig.width = 9}
g = dagitty('dag {
  BPMEDS [exposure]
  DEATH   [outcome]
  BPMEDS -> { DEATH }
  SEX  -> { EDUC BP CURSMOKE BMI DEATH }
  AGE  -> { EDUC BP DEATH }
  CURSMOKE -> { BP DEATH }
  BP -> { BPMEDS HEARTRTE }
  EDUC -> { BPMEDS CURSMOKE BMI DEATH }
  BMI -> { BP DEATH }
  HEARTRTE  ->  DEATH
  }')
# jpeg(file="dag.jpg", width = 9, height = 8, units = 'in', res = 300, quality = 100)
plot(g)
# dev.off()
```
```{r}
# Listing all adjustment sets
adjset = adjustmentSets(g, type = "minimal")
adjset
```
```{r}
data_df = read.csv('framingham_assignment.csv')
var_v = c('SEX', 'AGE', 'SYSBP', 'DIABP', 'BPMEDS', 'CURSMOKE', 'EDUC', 'BMI', 'HEARTRTE', 'DEATH')
data_df = data_df[!apply(data_df, MARGIN = 1, anyNA), var_v]
data_df$BP = 0
data_df$BP[(data_df$SYSBP >= 140) | (data_df$DIABP >= 90)] = 1
var_v = c('SEX', 'AGE', 'BP', 'BPMEDS', 'CURSMOKE', 'EDUC', 'BMI', 'HEARTRTE', 'DEATH')
print(summary(data_df))
for (c in c('SEX', 'BPMEDS', 'CURSMOKE', 'EDUC', 'DEATH', 'BP')){
  data_df[, c] = as.factor(data_df[, c])
}
print(summary(data_df))
```
```{r}
# Inspect data
ggpairs(data = data_df[, var_v])+ theme_bw()
```
```{r}
r = localTests(g, data_df,  type = 'cis.pillai')
r = r[p.adjust(r$p.value) < 0.05, ]
r = r[order(r$p.value), ]
plotLocalTestResults(r, bty = "n", xlim = c(-0.5, 0.5), axis.pars = list(las = 1, lty = 0))
```
```{r}
adj_g = dagitty('dag {
  BPMEDS [exposure]
  DEATH   [outcome]
  BPMEDS -> { DEATH }
  SEX  -> { BPMEDS EDUC BP CURSMOKE BMI HEARTRTE DEATH }
  AGE  -> { BPMEDS EDUC BP CURSMOKE BMI HEARTRTE DEATH }
  CURSMOKE -> { BP BMI HEARTRTE DEATH }
  BP -> { BPMEDS HEARTRTE DEATH }
  EDUC -> { BPMEDS CURSMOKE BMI HEARTRTE DEATH }
  BMI -> { BPMEDS BP HEARTRTE DEATH }
  HEARTRTE  ->  DEATH
  }')
r = localTests(adj_g, data_df,  type = 'cis.pillai')
r = r[p.adjust(r$p.value) < 0.05, ]
print(nrow(r))
adjset = adjustmentSets(adj_g, type = "minimal")
print(adjset)
```
```{r}
# jpeg(file="adjusted dag.jpg", width = 9, height = 8, units = 'in', res = 300, quality = 100)
plot(adj_g)
# dev.off()
```
# Week4
```{r}
outcome_r = glm(DEATH ~ BPMEDS + EDUC + BP + SEX + AGE + BMI + BPMEDS:EDUC + BPMEDS:BP + BPMEDS:SEX + BPMEDS:AGE + BPMEDS:BMI, data = data_df, family = 'binomial')
summary(outcome_r)
```
```{r}
n = nrow(data_df)
data_bpmeds0_df = data_df
data_bpmeds0_df$BPMEDS = as.factor(0)
data_bpmeds1_df = data_df
data_bpmeds1_df$BPMEDS = as.factor(1)
prob_death0 = predict(outcome_r, newdata = data_bpmeds0_df, type = 'response')
E_DEATH0 = mean(prob_death0)
prob_death1 = predict(outcome_r, newdata = data_bpmeds1_df, type = 'response')
E_DEATH1 = mean(prob_death1)
ATE = E_DEATH1 - E_DEATH0
print(c('E(DEATH(1))'=E_DEATH1, 'E(DEATH(0))'=E_DEATH0, ATE=ATE))
```
```{r}
std = stdGlm(fit = outcome_r, data = data_df, X = "BPMEDS")
print(summary(std))
print(summary(std, contrast = "difference", reference = 0))
```
```{r}
std1 = stdGlm(fit = outcome_r, data = data_df, X = "BPMEDS", subsetnew = BPMEDS == 1)
print(summary(std1))
print(summary(std1, contrast = "difference", reference = 0))
```
# Week5
```{r}
ps_r = glm(BPMEDS ~ EDUC + SYSBP + DIABP + SEX + AGE + BMI + CURSMOKE + HEARTRTE, data = data_df, family = 'binomial')
summary(ps_r)
```

```{r}
data_df$ps1 = predict(ps_r, newdata = data_df, type = "response")
data_df$ipw1 = 1/data_df$ps1 * (data_df$BPMEDS == 1) + 1/(1-data_df$ps1) * (data_df$BPMEDS == 0)
vars1 = c('SEX', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'EDUC', 'BMI', 'HEARTRTE')
covariates = data_df[, vars1]
table1 = bal.tab(covariates, treat = data_df$BPMEDS, weights = data_df$ipw1, method = "weighting", un = TRUE)
print(table1)
```
```{r}
p1 = ggplot(data = data_df[data_df$BPMEDS == 1, ], mapping = aes(x = ps1)) +
    geom_histogram(fill = 'red') + labs(title = 'BPMEDS = 1')
p2 = ggplot(data = data_df[data_df$BPMEDS == 0, ], mapping = aes(x = ps1)) + geom_histogram(fill = 'blue') + labs(title = 'BPMEDS = 0')
grid.arrange(p1, p2, nrow = 2)
summary(data_df$ps1)
```
```{r}
data_df$DEATH = as.numeric(data_df$DEATH)
EY1 = weighted.mean(x = data_df[data_df$BPMEDS == 1, "DEATH"], w = data_df[data_df$BPMEDS == 1, "ipw1"])
EY0 = weighted.mean(x = data_df[data_df$BPMEDS == 0, "DEATH"], w = data_df[data_df$BPMEDS == 0, "ipw1"])
ATE = EY1 - EY0
print(c(EY1 = EY1, EY0 = EY0, ATE = ATE))
```
```{r}
d.w = svydesign(~1, weights = data_df$ipw2, data = data_df)
w_reg = svyglm(DEATH ~ BPMEDS, design = d.w)
print(summary(w_reg))
print(confint(w_reg))
```
```{r}
summary(data_df$ipw1)
```
```{r}
ipw1_99th = quantile(data_df$ipw1, probs = 0.99)
data_df$ipw1_trunc = ifelse(data_df$ipw1 > ipw1_99th, ipw1_99th, data_df$ipw1)
EY1 = weighted.mean(x = data_df[data_df$BPMEDS == 1, "DEATH"], w = data_df[data_df$BPMEDS == 1, "ipw1_trunc"])
EY0 = weighted.mean(x = data_df[data_df$BPMEDS == 0, "DEATH"], w = data_df[data_df$BPMEDS == 0, "ipw1_trunc"])
ATE = EY1 - EY0
print(c(EY1 = EY1, EY0 = EY0, ATE = ATE))
```
```{r}
table2 = bal.tab(covariates, treat = data_df$BPMEDS, weights = data_df$ipw1_trunc, method = "weighting", un = TRUE)
print(table2)
```
