---
title: "weekly assignment 06"
author: "Xiang Li"
date: "2024/3/19"
output: pdf_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(tidy_opts = list(width.cutoff = 55), tidy = TRUE)
```
```{r}
library(readr)
library(nFactors)
library(GPArotation)
library(psych)
library(EFA.dimensions)
```
```{r}
data_df = read_delim("data_alexithymia2.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
dataX_df = data_df[, 4:23]
```
```{r}
prc_scl = prcomp(dataX_df, scale = TRUE)
summary(prc_scl)
```
Kaiser’s rule:
```{r}
ev = eigen(cor(dataX_df))
ev$values
```
Keep 6 components.

scree plot:
```{r}
pve_scl = summary(prc_scl)$importance[2,]
cum_pve_scl = summary(prc_scl)$importance[3,]
par(mfrow=c(1,2))
plot(pve_scl, type="b", xlab="Component number (sc.)", ylab="Proportion variance explained", ylim=c(0,1))
plot(cum_pve_scl, type="b", xlab="Number of components (sc.)", ylab="Cumulative prop. var. expl.", ylim=c(0,1))
nElem = length(cum_pve_scl)
ratios = (cum_pve_scl[2:(nElem-1)]-cum_pve_scl[1:(nElem-2)])/(cum_pve_scl[3:nElem]-cum_pve_scl[2:(nElem-1)])
ratios
nComponents_selected = which.max(ratios) + 1
nComponents_selected
```
Keep 2 components.

Horn’s parallel analysis:
```{r}
ev = eigen(cor(dataX_df))
ap = parallel(subject=nrow(dataX_df), var=ncol(dataX_df), rep=1000)
nS = nScree(x=ev$values, aparallel=ap$eigen$qevpea)
plotnScree(nS,main="")
```
```{r}
unrot = round(prc_scl$rotation[,1:6], 3)
unrot
prc_scl_rot = varimax(prc_scl$rotation[,1:6])
prc_scl_rot
```
