---
title: "week5-1"
author: "Xiang Li"
date: "2023/11/27"
output: pdf_document
---
```{r}
## Packages (install and invoke)
pkgs <- rownames(installed.packages())
if(!"bcgam" %in% pkgs) install.packages("bcgam")
if(!"car" %in% pkgs) install.packages("car")
if(!"faraway" %in% pkgs) install.packages("faraway")

library(bcgam)
library(car)
library(faraway)
library(matlib)
```
# Exercise 1
## a
```{r}
df = 4
Z = rnorm(1000)
chisq = rchisq(1000, df)
y = Z / sqrt(chisq/df)
hist(y, prob=TRUE, breaks=30, main="t-distribution with 4 df")
x = seq(min(y), max(y), by=0.01)
d = dt(x,df)
lines(d ~ x, type="l", col="red")
```
## b
```{r}
df = 25
Z = rnorm(1000)
chisq = rchisq(1000, df)
y = Z / sqrt(chisq/df)
hist(y, prob=TRUE, breaks=30, main="t-distribution with 25 df")
x = seq(min(y), max(y), by=0.01)
d = dt(x,df)
lines(d ~ x, type="l", col="red")
```
## c
```{r}
df1 = 4
df2 = 25
chisq1 = rchisq(1000, df1)
chisq2 = rchisq(1000, df2)
y = (chisq1/df1) / (chisq2/df2)
hist(y, prob=TRUE, breaks=30, main="F-distribution with 4 and 25 df")
x = seq(min(y), max(y), by=0.01)
d = df(x,df1, df2)
lines(d ~ x, type="l", col="red")
mean(y)
```
# Exercise 2
## a
```{r}
data(savings)
```
```{r}
SavingsReg <- lm(sr ~ pop15 + pop75 + dpi + ddpi, data=savings)
summary(SavingsReg)
```
## b
```{r}
(TSS <- sum((savings$sr-mean(savings$sr))^2)) #Total SS
(RSS <- sum(SavingsReg$residuals^2)) # Residual SS
(RegSS <- TSS - RSS) #Regression SS
(F <- ((RegSS)/4)/(RSS/45)) # Test statistic
pf(F,4,45, lower.tail = FALSE)
```
## c
```{r}
# Use R
confint(SavingsReg, level = 0.95)
# Manual calculations
X = model.matrix(SavingsReg)
y = savings$sr
b = solve(t(X) %*% X) %*% t(X) %*% y
e = y - X %*% b
n = nrow(X)
kp1 = ncol(X)
s2e = as.numeric(t(e) %*% e) / (n - kp1)
seb = (S2e * solve(t(X) %*% X)) ** 0.5
t_c = qt(0.975, df = n - kp1)
c(b[2]-t_c*seb[2, 2], b[2]+t_c*seb[2, 2])
```
## d
```{r}
newX = data.frame(pop15 = 30, pop75=2.5, dpi = 2000, ddpi = 4)
# Use R
#Confidence interval(for mean y)
pr1 = predict(SavingsReg, newdata = newX, interval = "confidence",se.fit=TRUE)
pr1$fit
#Prediction interval(for individual y)
pr2 = predict(SavingsReg, newdata = newX, interval = "prediction",se.fit=TRUE)
pr2$fit
# Manual calculations
#Confidence interval(for mean y)
newX = matrix(c(1, 30, 2.5, 2000, 4), nrow = 5, byrow = T)
coef = matrix(coef(SavingsReg), nrow = 1, byrow = T)
y_hat = as.numeric(coef %*% newX)
se = s2e ** 0.5
se_mean_y = se*as.numeric(t(newX) %*% solve(t(X) %*% X) %*% newX) ** 0.5
t_c = qt(0.975, n-kp1)
c(y_hat-t_c*se_mean_y, y_hat+t_c*se_mean_y)
#Prediction interval(for individual y)
se_ind_y = se*(as.numeric(t(newX) %*% solve(t(X) %*% X) %*% newX) + 1) ** 0.5
c(y_hat-t_c*se_ind_y, y_hat+t_c*se_ind_y)
```
## e
```{r}
SavingsReg0 <- lm(sr ~ pop15 + dpi , data=savings)
summary(SavingsReg0)
```
```{r}
(RSS <- sum(SavingsReg$residuals^2)) # Residual SS of the full model
(RSS0 <- sum(SavingsReg0$residuals^2)) # Residual SS of the reduced model
(F <- ((RSS0 - RSS)/2)/(RSS/45)) # Test statistic
pf(F,2,45, lower.tail = FALSE)
```
```{r}
anova(SavingsReg, SavingsReg0)
```
## f.
```{r}
SavingsReg01 <- lm(sr ~ I(pop15+pop75)+dpi+ddpi,savings)
summary(SavingsReg01)
anova(SavingsReg, SavingsReg01)
```
# Exercise 3.
## a
```{r}
SatReg <-lm(total ~ expend + ratio + salary, data=sat)
summary(SatReg)
2*pt(-1.878, 42, lower.tail = TRUE)
```
## b
```{r}
SatReg0 <-lm(total ~ expend + ratio, data=sat)
summary(SatReg0)
anova(SatReg, SatReg0)
```
## c
```{r}
pt(-1.878, 46)
```
## d
```{r}
1 - pt(-1.878, 46)
```
## f
```{r}
Upp <- coefficients(summary(SatReg))[,1] + qt(0.975,46 ) * coefficients(summary(SatReg))[,2]
Low <- coefficients(summary(SatReg))[,1] -  qt(0.975,46 ) * coefficients(summary(SatReg))[,2]
cbind(Low, Upp)
confint(SatReg)
```
## g
```{r}
SatReg.wtakers <-lm(total ~ expend + ratio + salary + takers, data=sat)
summary(SatReg.wtakers)
anova(SatReg, SatReg.wtakers)
```
