---
title: "week5-3"
author: "Xiang Li"
date: "2023/11/29"
output: pdf_document
---
```{r}
## Packages (install and invoke)
pkgs <- rownames(installed.packages())
if(!"EnvStats" %in% pkgs) install.packages("EnvStats")
if(!"MASS" %in% pkgs) install.packages("MASS")
if(!"car" %in% pkgs) install.packages("car")
if(!"faraway" %in% pkgs) install.packages("faraway")
if(!"splines" %in% pkgs) install.packages("splines")
```
```{r}
library(EnvStats)
library(car)
library(faraway)
library(splines)
library(MASS)
```
# Exercise 1.
```{r}
set.seed(12345)
n <- 20
x <- runif(n)
eps1 <- rnorm(n)
eps2 <- rnorm(n, sd=sqrt(2*x))
eps3 <- rchisq(n,2)-2
y1 <- 5 + 8*x + eps1
y2 <- 5 + 8*x + eps2
y3 <- 5 + 8*x + eps3
lmo1 <- lm(y1 ~ x)
std.res1 <- rstandard(lmo1)
lmo2 <- lm(y2 ~ x)
std.res2 <- rstandard(lmo2)
lmo3 <- lm(y3 ~ x)
std.res3 <- rstandard(lmo3)
q1<-qqPlot(std.res1)
q2<-qqPlot(std.res2)
q3<-qqPlot(std.res3);
plot(std.res1 ~ fitted(lmo1))
plot(std.res2 ~ fitted(lmo2))
plot(std.res3 ~ fitted(lmo3))
```
```{r}
set.seed(6789)
n <- 100
x <- runif(n)
eps1 <- rnorm(n)
eps2 <- rnorm(n, sd=sqrt(2*x))
eps3 <- rchisq(n,2)-2
y1 <- 5 + 8*x + eps1
y2 <- 5 + 8*x + eps2
y3 <- 5 + 8*x + eps3
lmo1 <- lm(y1 ~ x)
std.res1 <- rstandard(lmo1)
lmo2 <- lm(y2 ~ x)
std.res2 <- rstandard(lmo2)
lmo3 <- lm(y3 ~ x)
std.res3 <- rstandard(lmo3)
q1<-qqPlot(std.res1)
q2<-qqPlot(std.res2)
q3<-qqPlot(std.res3);
plot(std.res1 ~ fitted(lmo1))
plot(std.res2 ~ fitted(lmo2))
plot(std.res3 ~ fitted(lmo3))
```
# Exercise 2.
## a
```{r}
X1 <- runif(100)
 X2 <- runif(100)
 epsilon <- rnorm(100)
 Y <- X1 + X2 + 0.1*epsilon
 lmo.a <- lm(Y ~ X1 + X2)
 crPlot(lmo.a,X1) # function from car library
 crPlot(lmo.a,X2)
```
```{r}
res <- residuals(lmo.a)
respluscomp1 <- residuals(lmo.a) + coef(lmo.a)[2]*X1
respluscomp2 <- residuals(lmo.a) + coef(lmo.a)[3]*X2
plot(respluscomp1 ~ X1)
plot(respluscomp2 ~ X2)
```
## b
```{r}
X1 <- runif(100)
delta <- rnorm(100)
epsilon <- rnorm(100)
X2 <- X1 + 0.1*delta
Y <- X1 + X2 + 0.1*epsilon
lmo.b <- lm(Y ~ X1 + X2)
crPlot(lmo.b,X1)
crPlot(lmo.b,X2)
```
## c
```{r}
X1 <- runif(100)
X2 <- runif(100)
epsilon <- rnorm(100)
Y <- 2*(X1-0.5)^2 + X2 + 0.1*epsilon
lmo.c <- lm(Y ~ X1 + X2)
crPlot(lmo.c,X1)
crPlot(lmo.c,X2)
```
# Exercise 3
## a
```{r}
data(savings)
g <- lm(sr ~ pop15+pop75+dpi+ddpi,savings)
summary(g)
bc <- boxcox(g,plotit=T)
#We can narrow the range of lambda, to make it more visible
bc <- boxcox(g,plotit=T,lambda=seq(0.5,1.5,by=0.1))
# Exact lambda
lambda <- bc$x[which.max(bc$y)]
lambda
```
# Exercise 4
## a
```{r}
data(gala)
g <- lm(Species ~ Area + Elevation + Nearest + Scruz + Adjacent,gala)
summary(g)
summary(g)$r.squared

qqPlot(gala$Species)
#car::qqPlot(bc_Species)
```
## c
```{r}
bc <- boxcox(g,plotit=T)
bc <- boxcox(g,lambda=seq(0.0,1.0,by=0.05),plotit=T)
lambda <- bc$x[which.max(bc$y)]
lambda

bc_Species <- (gala$Species^lambda - 1) / lambda
```
```{r}
qqPlot(bc_Species)
```
# Exercise 5
## a
```{r}
olm <- lm(temp ~ year, aatemp)
summary(olm)
plot(temp ~ year, data=aatemp)
abline(olm)
```
```{r}
#orthogonal polynomials
plm.10 <- lm(temp ~ poly(year, 10), data=aatemp)
summary(plm.10)
```
```{r}
plm.9 <- lm(temp ~ poly(year, 9), aatemp)
plm.8 <- lm(temp ~ poly(year, 8), aatemp)
plm.7 <- lm(temp ~ poly(year, 7), aatemp)
plm.6 <- lm(temp ~ poly(year, 6), aatemp)
plm.5 <- lm(temp ~ poly(year, 5), aatemp)
plm.4 <- lm(temp ~ poly(year, 4), aatemp)
plm.3 <- lm(temp ~ poly(year, 3), aatemp)
plm.2 <- lm(temp ~ poly(year, 2), aatemp)
summary(plm.9)
summary(plm.8)
summary(plm.7)
summary(plm.6)
summary(plm.5)
```
```{r}
plot(temp ~ year, data=aatemp)
lines(aatemp$year, fitted(plm.5))
d2020 <- data.frame(year=2020)
predict(plm.5, d2020)
```
